Repository stdevel/katprep, pull requests merged in 2018-06, with the labels that each got.

#46 Feature suppress reboot issue39
  katprep/maintenance.py
Labels: enhancement

#47 Fixed a bug where detecting physical hosts was not working properly, …
  katprep/snapshot.py
Labels: bug

#48 dont-repeat-yourself
  katprep/clients/PyvmomiClient.py
Labels: enhancement, style

#49 Added parameter -P / --auth-password,
  katprep/__init__.py
  katprep/maintenance.py
  katprep/parameters.py
  katprep/populate.py
  katprep/snapshot.py
Labels: enhancement

#51 Feature ip issue35
  katprep/clients/Icinga2APIClient.py
  katprep/clients/LibvirtClient.py
  katprep/clients/NagiosCGIClient.py
  katprep/clients/PyvmomiClient.py
  katprep/clients/katprep_shared.py
  katprep/populate.py
  katprep/snapshot.py
Labels: enhancement

#53 Removed some pitfalls for unregistered content hosts
  katprep/snapshot.py
Labels: bug

#54 Bug nagios downtime issue41
  katprep/clients/NagiosCGIClient.py
  katprep/maintenance.py
  katprep/populate.py
Labels: bug, enhancement

#55 Bug errata reboot issue40
  katprep/maintenance.py
Labels: bug, enhancement

#56 Added code for blacklisting wildcards
  katprep/maintenance.py
Labels: enhancement

#57 Unit tests issue13
  katprep/clients/ForemanAPIClient.py
  katprep/clients/Icinga2APIClient.py
  katprep/clients/LibvirtClient.py
  katprep/clients/NagiosCGIClient.py
  katprep/clients/PyvmomiClient.py
  katprep/clients/__init__.py
  katprep/maintenance.py
  katprep/parameters.py
  katprep/populate.py
  katprep/snapshot.py
  tests/.gitignore
  tests/ForemanAPIClientTest.py
  tests/Icinga2APIClientTest.py
  tests/NagiosCGIClientTest.py
  tests/PyvmomiClientTest.py
  tests/README.md
  tests/__init__.py
  tests/fman_config.json.tmpl
  tests/icinga2_config.json.tmpl
  tests/nagios_config.json.tmpl
  tests/test_katprep.py
Labels: documentation, style

#58 Added code for installing package upgrades
  katprep/maintenance.py
Labels: enhancement

#59 Feature spacewalk support
  katprep/clients/SpacewalkAPIClient.py
  tests/SpacewalkAPIClientTest.py
  tests/spw_config.json.tmpl
Labels: enhancement

#66 Feature maintenance only filter issue63
  katprep/maintenance.py
Labels: enhancement

#69 Feature revert issue6
  doc/manpages/src/katprep_maintenance.1.md
  doc/source/man/katprep_maintenance.1.rst
  docs/_modules/clients/PyvmomiClient.html
  docs/_modules/katprep/maintenance.html
  docs/_sources/man/katprep_maintenance.1.txt
  docs/katprep.clients.html
  docs/katprep.html
  docs/man/katprep_maintenance.1.html
  docs/searchindex.js
  katprep/clients/PyvmomiClient.py
  katprep/maintenance.py
Labels: enhancement

#70 Feature unit tests issue13
  doc/manpages/src/katprep.1.md
  doc/source/changelog.rst
  doc/source/man/katprep.1.rst
  docs/_modules/clients/LibvirtClient.html
  docs/_sources/changelog.txt
  docs/_sources/man/katprep.1.txt
  docs/changelog.html
  docs/katprep.clients.html
  docs/katprep.html
  docs/man/katprep.1.html
  docs/searchindex.js
  katprep/clients/LibvirtClient.py
  tests/.gitlab-ci.yml
  tests/LibvirtClientTest.py
  tests/README.md
  tests/libvirt_config.json.tmpl
  tests/tmpl-katprep-centos7/Dockerfile
  tests/update_docker.sh
Labels: documentation, enhancement
